module.exports = {
	content: ["site/**/*.{html,js,php}", "admin/**/*.{html,js,php}", "register.php", "reset_password.php", "recover_password.php", "verify_account.php"],
	mode: "jit",
	purge: ["site/**/*.{html,js,php}", "admin/**/*.{html,js,php}", "register.php", "reset_password.php", "recover_password.php", "verify_account.php"],
	theme: {
		extend: {},
		screens: {
			sm: { min: "375px", max: "767px" },
			md: { min: "768px", max: "1365px" },
			lg: "1366px",
		},
	},
	plugins: [require("daisyui")],
	daisyui: {
		styled: true,
		themes: true,
		base: true,
		utils: true,
		logs: true,
		rtl: false,
		prefix: "",
		darkTheme: "dark",
	},
	daisyui: {
		themes: [
			"light",
			"dark",
			"cupcake",
			"bumblebee",
			"emerald",
			"corporate",
			"synthwave",
			"retro",
			"cyberpunk",
			"valentine",
			"halloween",
			"garden",
			"forest",
			"aqua",
			"lofi",
			"pastel",
			"fantasy",
			"wireframe",
			"black",
			"luxury",
			"dracula",
			"cmyk",
			"autumn",
			"business",
			"acid",
			"lemonade",
			"night",
			"coffee",
			"winter",
		],
	},
};
